force-app/main/default/objects/SAIdEnq__c/SAIdEnq__c.object-meta.xml
<CustomObject>
    <label>SAIdEnq</label>
    <nameField>
        <label>SAIdEnq Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAIdEnqs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAIdEnq__c/fields/SAId__c.field-meta.xml
<CustomField>
    <fullName>SAId__c</fullName>
    <label>SAId</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdCitizenShip__c.field-meta.xml
<CustomField>
    <fullName>SAIdCitizenShip__c</fullName>
    <label>SAIdCitizenShip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdDob__c.field-meta.xml
<CustomField>
    <fullName>SAIdDob__c</fullName>
    <label>SAIdDob</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdGender__c.field-meta.xml
<CustomField>
    <fullName>SAIdGender__c</fullName>
    <label>SAIdGender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdNoSearched__c.field-meta.xml
<CustomField>
    <fullName>SAIdNoSearched__c</fullName>
    <label>SAIdNoSearched</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SAIdGetPublicHolidayController.cls
public class SAIdGetPublicHolidayController {
    @AuraEnabled
     /**
     * @description to get public holidays
     * @param inputSAId
     * @return SAIdEnq__c
     */
    public static SAIdEnq__c SAIdGetPublicHoliday(string inputSAId){
        SAIdEnq__c saIdExists = SAIdSelect.SAIdSelectQuery(inputSAId); 
        if(saIdExists != null){
            saIdExists.SAIdNoSearched__c++;
            update saIdExists;
            return saIdExists;
        }
        else {
            string tmpinputSAId = inputSAId;
            SAIdEnq__c saiIdEnq = new SAIdEnq__c();
            saiIdEnq.SAId__c = inputSAId;
            saiIdEnq.SAIdDob__c = inputSAId.substring(0,6);
            Integer genderCheck = Integer.valueOf(inputSAId.substring(6,10));
            if (genderCheck > 4999){
                saiIdEnq.SAIdGender__c = 'Male';
            }
            else {
                saiIdEnq.SAIdGender__c = 'Female';
            }
            Integer citizenshipCheck = Integer.valueOf(inputSAId.substring(10,11));
            if(citizenshipCheck == 0){
                 saiIdEnq.SAIdCitizenShip__c='SA Citizen';
            }else if (citizenshipCheck == 1) {
            	saiIdEnq.SAIdCitizenShip__c='Perminant Citizen';
            }
            saiIdEnq.SAIdNoSearched__c = 1;
            Insert saiIdEnq;
            return saiIdEnq;
            
        }    
    }
     /**
     * @description calling holiday api service
     * @param inputSAId
     * @return string
     */
   @AuraEnabled
    public static string getPublicHolidayApi(string inputSAId){
         HttpResponse reqRespService =  SAIdHttpsServiceCall.SAIdHttpsServiceCalling(inputSAId);
        if (reqRespService != null){
            return reqRespService.getBody();
        }
        
        return null;
    }
        

}