force-app/main/default/objects/SAIdEnq__c/SAIdEnq__c.object-meta.xml
<CustomObject>
    <label>SAIdEnq</label>
    <nameField>
        <label>SAIdEnq Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAIdEnqs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAIdEnq__c/fields/SAId__c.field-meta.xml
<CustomField>
    <fullName>SAId__c</fullName>
    <label>SAId</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdCitizenShip__c.field-meta.xml
<CustomField>
    <fullName>SAIdCitizenShip__c</fullName>
    <label>SAIdCitizenShip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdDob__c.field-meta.xml
<CustomField>
    <fullName>SAIdDob__c</fullName>
    <label>SAIdDob</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdGender__c.field-meta.xml
<CustomField>
    <fullName>SAIdGender__c</fullName>
    <label>SAIdGender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAIdEnq__c/fields/SAIdNoSearched__c.field-meta.xml
<CustomField>
    <fullName>SAIdNoSearched__c</fullName>
    <label>SAIdNoSearched</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SAIdSelect.cls
public class SAIdSelect {
    /**
     * @description checks SA Id exists or not
     * @param inputSAId
     * @return SAIdEnq__c
     */
    public static SAIdEnq__c SAIdSelectQuery(string inputSAId){
        try {
            SAIdEnq__c saIdExists  = [select id, SAId__c,SAIdDob__c,SAIdGender__c, SAIdNoSearched__c,SAIdCitizenShip__c from SAIdEnq__c where SAId__c=:inputSAId limit 1];
            if (saIdExists != null){
            return saIdExists;
            }
            return null;
        }
        catch (System.Exception e){
            system.debug('Exception occured  ' + e.getMessage());
            return null;
        }
    }

}